### ISSUE TITLE
Missing 'min_gap`, `max gap`, `max_span` and `window size` time constraints in AlgoGSP implementation

### ISSUE THREAD

**Issue by dmeoli** [jacksonpradolima/SPMF#1]
as specified in the [original paper](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=9E170B23E625183064A202E50FD5ED43?doi=10.1.1.217.7520&rep=rep1&type=pdf) and in Kumar's book, from page 437 to 439

**Comment by dmeoli** [comment]
The GSP algorithm with time constraints can be found [here](http://www.philippe-fournier-viger.com/spmf/HirateYamana.php)

**Comment by jacksonpradolima** [comment]
Dear @dmeoli 

This repository is only a mirror of the original project available at [http://www.philippe-fournier-viger.com/spmf/](http://www.philippe-fournier-viger.com/spmf/)

I am glady you found the answer!

Best regards
